services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - 80:5173
    environment:
      - VITE_BACKEND_URL=http://ec2-98-88-225-135.compute-1.amazonaws.com
    # Match the WORKDIR from your Dockerfile
    working_dir: /usr/local/app
    volumes:
      - ./frontend:/usr/local/app
      # This "Anonymous Volume" protects the container's node_modules
      # from being overwritten by your host machine
      - /usr/local/app/node_modules

  backend:
    build:
      context: ./backend
    environment:
      PYTHONUNBUFFERED: 1

    restart: always
    ports:
      - 8000:8000

